import { ExperienceCustomizationState } from "./types";

export const defaultExperienceStyles: ExperienceCustomizationState = {
  cardLayout: "default",
  cardBorderRadius: 16,
  cardPadding: 24,
  cardSpacing: 32,
  containerWidth: "full",
  titleSize: "lg",
  titleWeight: "bold",
  descriptionSize: "sm",
  textAlignment: "left",
  hoverEffects: true,
  glowEffect: true,
  borderGlow: false,
  backgroundOpacity: 0,
  borderWidth: 1,
  animationStyle: "scale",
  animationSpeed: 500,
  staggerDelay: 200,
  techStackVisible: true,
  techStackStyle: "pills",
  techStackSize: "sm",
  timelineStyle: "line",
  timelinePosition: "left",
  timelineWidth: 2,
  timelineColor: "#f97316",
  dotSize: "md",
  dotStyle: "circle",
  locationBadge: true,
  dateBadge: true,
  badgeStyle: "default",
  sideAccent: true,
  sideAccentWidth: 4,
  sideAccentColor: "#f97316",
};
