import { ExperienceCustomizationState } from "@/types/experience/portfolio";

export const defaultExperienceStyles: ExperienceCustomizationState = {
  cardLayout: "default",
  cardBorderRadius: 16,
  cardPadding: 24,
  cardSpacing: 32,
  containerWidth: "full",
  titleSize: "lg",
  titleWeight: "bold",
  descriptionSize: "sm",
  textAlignment: "left",
  hoverEffects: true,
  glowEffect: true,
  borderGlow: false,
  backgroundOpacity: 0,
  borderWidth: 1,
  animationStyle: "scale",
  animationSpeed: 500,
  staggerDelay: 200,
  techStackVisible: true,
  techStackStyle: "pills",
  techStackSize: "sm",
  timelineStyle: "line",
  timelinePosition: "left",
  timelineWidth: 2,
  timelineColor: "#f97316",
  dotSize: "md",
  dotStyle: "circle",
  locationBadge: true,
  dateBadge: true,
  badgeStyle: "default",

  // Side Accent
  sideAccent: true,
  sideAccentWidth: 4,
  sideAccentColor: "primary",

  // Missing properties added during unification
  maxWidth: "full",
  containerPadding: 4,
  backgroundColor: "transparent",
  cardBackground: "glass",
  cardBorderColor: "gray-200",
  cardBorderStyle: "none",
  cardShadow: "none",
  titleColor: "primary",
  titleAlignment: "left",
  descriptionColor: "text-secondary",
  descriptionVisible: true,
  headerVisible: true,
  companyNameSize: "lg",
  companyNameWeight: "bold",
  companyNameColor: "text-primary",
  roleSize: "md",
  roleWeight: "medium",
  roleColor: "text-secondary",
  dateFormat: "month-year",
  dateColor: "text-tertiary",
  locationVisible: true,
  locationColor: "text-tertiary",
  descriptionTextSize: "sm",
  descriptionTextColor: "text-secondary",
  hoverScale: false,
  hoverShadow: false,
  cardHoverEffect: "none",
  staggerAnimation: true,
  entranceAnimation: "slideIn",
  alternatingLayout: false,
  techStackLimit: 10,
  techStackColor: "gray",
  techStackShowIcons: true,
};