import { EducationCustomizationState } from "@/types/interfaces/EducationCustomizationState";

export const defaultNeoSparkEducationStyles: EducationCustomizationState = {
    cardStyle: "default",
    cardBorderRadius: 16,
    cardPadding: 24,
    cardSpacing: 32,
    titleSize: "lg",
    titleWeight: "bold",
    textAlignment: "left",
    hoverEffects: true,
    glowEffect: true,
    borderGlow: false,
    backgroundOpacity: 0,
    borderWidth: 1,
    animationStyle: "fade",
    animationSpeed: 500,
    staggerDelay: 100,
    showInstitution: true,
    showDates: true,
    showLocation: true,
    showDescription: true,
    descriptionStyle: "expand",
    accentLine: true,
    accentLineStyle: "gradient",
    accentLineWidth: 4,
    accentLineColor: "#f97316",
    cardShadow: false,
    shadowIntensity: 1,
    backgroundBlur: false,
    blurIntensity: 10,
    showArrow: true,
    arrowStyle: "animated",
    dateFormat: "short",
    institutionStyle: "minimal",
    institutionSize: "sm",
};
