import { TechnologiesCustomizationState } from "@/types/interfaces/TechnologiesCustomizationState";

export const defaultNeoSparkTechnologiesStyles: TechnologiesCustomizationState = {
    layout: "grid",
    gridColumns: 4,
    gap: 24,
    containerWidth: "2xl",
    cardStyle: "gradient",
    cardBorderRadius: 12,
    cardPadding: 20,
    cardShadow: "medium",
    borderWidth: 1,
    backgroundOpacity: 10,
    showIcons: true,
    iconSize: 40,
    showLabels: true,
    labelPosition: "bottom",
    labelSize: "sm",
    labelWeight: "medium",
    textAlignment: "center",
    animationStyle: "fade",
    animationSpeed: 300,
    staggerAnimation: true,
    hoverEffects: true,
    cardHoverEffect: "lift",
    marqueeDirection: "left",
    marqueeSpeed: 50,
    pauseOnHover: true,
};
