import { ExperienceCustomizationState } from "./portfolio";

export const defaultNeoSparkExperienceStyles: ExperienceCustomizationState = {

    //layout
    cardLayout: "glass",
    cardSpacing: 32,
    cardBorderRadius: 16,
    cardPadding: 24,
    containerWidth: "full",
    titleSize: "lg",
    titleWeight: "bold",
    descriptionSize: "sm",
    textAlignment: "left",
    hoverEffects: true,
    glowEffect: true,
    borderGlow: false,
    backgroundOpacity: 0,
    borderWidth: 1,
    animationStyle: "scale",
    animationSpeed: 500,
    staggerDelay: 200,
    techStackVisible: true,
    techStackStyle: "pills",
    techStackSize: "sm",
    timelineStyle: "gradient",
    timelinePosition: "left",
    timelineWidth: 2,
    timelineColor: "#f97316",
    dotSize: "md",
    dotStyle: "hexagon",
    locationBadge: true,
    dateBadge: true,
    badgeStyle: "default",

    // Missing properties added during unification
    maxWidth: "full",
    containerPadding: 4,
    backgroundColor: "transparent",
    cardBackground: "glass",
    cardBorderColor: "gray-200",
    cardBorderStyle: "none",
    cardShadow: "none",
    titleColor: "primary",
    titleAlignment: "left",
    descriptionColor: "text-secondary",
    descriptionVisible: true,
    headerVisible: true,
    companyNameSize: "lg",
    companyNameWeight: "bold",
    companyNameColor: "text-primary",
    roleSize: "md",
    roleWeight: "medium",
    roleColor: "text-secondary",
    dateFormat: "month-year",
    dateSize: "sm",
    dateWeight: "medium",
    dateColor: "text-tertiary",
    locationVisible: true,
    locationSize: "sm",
    locationWeight: "normal",
    locationColor: "text-tertiary",
    descriptionTextSize: "sm",
    descriptionTextWeight: "normal",
    descriptionTextColor: "text-secondary",
    hoverScale: false,
    hoverShadow: false,
    cardHoverEffect: "none",
    staggerAnimation: true,
    entranceAnimation: "slideIn",
    alternatingLayout: false,
    techStackLimit: 10,
    techStackColor: "gray",
    techStackShowIcons: true,
    sideAccent: false,
    sideAccentColor: "blue-500",
    sideAccentWidth: 4,
};
