import { ContactCustomizationState } from "./portfolio";

export const defaultNeoSparkContactStyles: ContactCustomizationState = {
    layout: "grid",
    gridColumns: 4,
    cardLayout: "stacked",
    cardSize: "default",
    containerWidth: "wide",
    cardSpacing: 24,
    cardStyle: "gradient",
    cardBorderRadius: 12,
    cardPadding: 8,
    iconSize: 32,
    iconStyle: "outline",
    backgroundOpacity: 100,
    borderWidth: 1,
    showLabels: true,
    showDescriptions: true,
    textAlignment: "center",
    animationStyle: "scale",
    animationSpeed: 300,
    staggerDelay: 100,
    hoverEffects: true,
    copyToClipboard: false,
    openInNewTab: true,
};
