import { TechnologiesCustomizationState } from "@/types/interfaces/TechnologiesCustomizationState";

export const defaultWindowsTechnologiesStyles: TechnologiesCustomizationState = {
    layout: "grid",
    gridColumns: 5,
    gap: 16,
    containerWidth: "full",
    cardStyle: "default",
    cardBorderRadius: 6,
    cardPadding: 16,
    cardShadow: "light",
    borderWidth: 1,
    backgroundOpacity: 5,
    showIcons: true,
    iconSize: 32,
    showLabels: true,
    labelPosition: "bottom",
    labelSize: "xs",
    labelWeight: "medium",
    textAlignment: "center",
    animationStyle: "scale",
    animationSpeed: 300,
    staggerAnimation: true,
    hoverEffects: true,
    cardHoverEffect: "glow",
    marqueeDirection: "left",
    marqueeSpeed: 40,
    pauseOnHover: true,
};
