import { ExperienceCustomizationState } from "../interfaces/ExperienceCustomizationState";
import { ProjectsCustomizationState } from "../interfaces/ProjectsCustomizationState";
import { EducationCustomizationState } from "../interfaces/EducationCustomizationState";
import { defaultAcademicSidebarStyles } from "./sidebar";

export const defaultAcademicStyles = {
    sidebar: defaultAcademicSidebarStyles,
    hero: {
        backgroundColor: "#ffffff",
        textColor: "#1a202c",
        fontFamily: "Merriweather, serif",
        titleSize: "4xl",
        titleWeight: "bold",
        summarySize: "lg",
        summaryWeight: "normal",
        lineHeight: "relaxed",
    },
    section: {
        backgroundColor: "#ffffff",
        textColor: "#2d3748",
        headingColor: "#1a202c",
        borderColor: "#e2e8f0",
    },
    typography: {
        headingFont: "Merriweather, serif",
        bodyFont: "Inter, sans-serif",
    },
    experience: {
        cardLayout: "default",
        cardBorderRadius: 8,
        cardPadding: 24,
        cardSpacing: 24,
        containerWidth: "wide",
        maxWidth: "2xl",
        containerPadding: 64,
        backgroundColor: "white",
        cardBackground: "transparent",
        cardBorderColor: "#e2e8f0",
        cardBorderStyle: "none",
        cardShadow: "none",
        titleSize: "xl",
        titleWeight: "bold",
        titleColor: "#111827", // gray-900
        titleAlignment: "left",
        descriptionSize: "md",
        descriptionColor: "#4b5563", // gray-600
        descriptionVisible: true,
        textAlignment: "left",
        headerVisible: true,
        companyNameSize: "lg",
        companyNameWeight: "semibold",
        companyNameColor: "#111827", // gray-900
        roleSize: "xl",
        roleWeight: "bold",
        roleColor: "#111827", // gray-900
        dateFormat: "month-year",
        dateSize: "sm",
        dateWeight: "medium",
        dateColor: "#6b7280", // gray-500
        locationVisible: true,
        locationSize: "sm",
        locationWeight: "normal",
        locationColor: "#6b7280", // gray-500
        descriptionTextSize: "md",
        descriptionTextWeight: "normal",
        descriptionTextColor: "#4b5563", // gray-600
        hoverEffects: false,
        hoverScale: false,
        hoverShadow: false,
        cardHoverEffect: "none",
        glowEffect: false,
        borderGlow: false,
        backgroundOpacity: 1,
        borderWidth: 0,
        animationStyle: "none",
        animationSpeed: 500,
        staggerDelay: 100,
        staggerAnimation: false,
        entranceAnimation: "none",
        alternatingLayout: false,
        techStackVisible: true,
        techStackStyle: "minimal",
        techStackSize: "sm",
        techStackLimit: 5,
        techStackColor: "gray",
        techStackShowIcons: false,
        timelineStyle: "line",
        timelinePosition: "left",
        timelineWidth: 2,
        timelineColor: "#e2e8f0",
        dotSize: "md",
        dotStyle: "circle",
        locationBadge: false,
        dateBadge: false,
        badgeStyle: "minimal",
        sideAccent: false,
        sideAccentColor: "#3b82f6", // blue-500
        sideAccentWidth: 4,
    } as ExperienceCustomizationState,
    projects: {
        layout: "single",
        gridColumns: 1,
        backgroundColor: "white",
        cardSpacing: 32,
        cardBorderRadius: 8,
        imageBorderRadius: 8,
        cardBackground: "transparent",
        cardBorder: "none",
        cardStyle: "minimal",
        imageAspectRatio: "wide",
        imageHeight: 200,
        githubButtonStyle: "minimal",
        liveButtonStyle: "minimal",
        buttonBorderRadius: 4,
        techStackStyle: "minimal",
        animationSpeed: 500,
        titleAlignment: "left",
        cardPadding: 0,
        imageOverlay: false,
        imagePosition: "left",
        hoverEffects: false,
        glowEffect: false,
        borderWidth: 0,
        titleSize: "xl",
        titleWeight: "bold",
        descriptionSize: "md",
        descriptionWeight: "normal",
    } as ProjectsCustomizationState,
    education: {
        cardStyle: "minimal",
        cardBorderRadius: 8,
        cardPadding: 24,
        cardSpacing: 24,
        titleSize: "xl",
        titleWeight: "bold",
        textAlignment: "left",
        hoverEffects: false,
        glowEffect: false,
        borderGlow: false,
        backgroundOpacity: 1,
        borderWidth: 0,
        animationStyle: "none",
        animationSpeed: 500,
        staggerDelay: 100,
        showInstitution: true,
        showDates: true,
        showLocation: true,
        showDescription: true,
        descriptionStyle: "plain",
        accentLine: true,
        accentLineStyle: "solid",
        accentLineWidth: 2,
        accentLineColor: "#e2e8f0",
        cardShadow: false,
        shadowIntensity: 0,
        backgroundBlur: false,
        blurIntensity: 0,
        showArrow: false,
        arrowStyle: "none",
        dateFormat: "year",
        institutionStyle: "minimal",
        institutionSize: "md",
        backgroundColor: "#ffffff",
        borderColor: "#e2e8f0",
        headingColor: "#1a202c",
    } as EducationCustomizationState,
};

export interface AcademicCustomization {
    sidebar?: typeof defaultAcademicSidebarStyles;
    hero?: typeof defaultAcademicStyles.hero;
    section?: typeof defaultAcademicStyles.section;
    typography?: typeof defaultAcademicStyles.typography;
    experience?: ExperienceCustomizationState;
    projects?: ProjectsCustomizationState;
    education?: EducationCustomizationState;
}
